### ISSUE TITLE
Emails are not delivered, some configuration problem

### ISSUE THREAD

**Issue by Everred** [Vinai/customer-activation#86]
Hello, I'm new to magento and I don't know how to start this. I have a local fresh installed magento 1.9, I added this module, and it is working except that emails are not sent (or not delivered). I'm new to ubuntu and linux system but I think I lack some functionality that sends those emails or it's not properly configured. I've installed sendmail but I did not change any configuration file after there so probably that's why mailes were not sent, so I tried to find in admin panel where is the mailbox configuration. I put email address in system->config->general but there was no place to put password, so it's still not sending. What am I suppose to do to make it send emails? Sorry if that is stupid question, I just don't know and I'm trying to find an answer for whole day...

Edit: I checked closed issues and there was this #64  but I have required files in app/locale.

**Comment by Vinai** [comment]
Magento sends emails via cron since version 1.9.1, so probably you are missing that part of the setup.
How to set up cron for Magento is out of scope, but http://magento.stackexchange.com/a/56375/766 seems useful, even though a bit more verbose then actually is necessary. I'm sure google will help you find more information. I know there also is a page on that setup in the official Magento documentation.
